version: '3.4'

services:
  mr.api:
    image: ${DOCKER_REGISTRY-}mrapi
    build:
      context: .
      dockerfile: MR.Api/Dockerfile
    ports:
      - "5000:80"
      - "4443:443"

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    ports:
      - '3306:3306'
    environment:
        MYSQL_DATABASE: MovieReviewer
        MYSQL_ROOT_PASSWORD: root
    volumes:
        - dbdata:/var/lib/mysql

  pma:
    depends_on:
    - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
    - '8085:80'
    environment:
      PMA_HOST: db

volumes:
  dbdata: